name: Haskell CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    # run at the start of every day
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ${{ matrix.os }} 
    strategy:
      matrix:
        ghc: ['8.6', '8.8', '8.10', '9.0']
        cabal: ['3.0', '3.2', '3.4']
        os: [ubuntu-20.04]
        exclude:
                # GHC 9.0 not supported by cabal 3.0 and 3.2
                - ghc: '9.0'
                  cabal: '3.0'
                - ghc: '9.0'
                  cabal: '3.2'
    name: ${{ matrix.os }} GHC ${{ matrix.ghc }} Cabal ${{ matrix.cabal }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install icestorm prerequisites
      run: |
        sudo apt-get update
        sudo apt-get install build-essential clang bison flex libreadline-dev gawk tcl-dev libffi-dev git graphviz xdot pkg-config python python3 libftdi-dev qt5-default python3-dev libboost-all-dev cmake libeigen3-dev

    - name: Checkout icestorm
      uses: actions/checkout@v2
      with:
        repository: YosysHQ/icestorm
        path: icestorm

    - name: Install icestorm
      working-directory: icestorm
      run: |
        make
        sudo make install

    - name: Checkout nextpnr
      uses: actions/checkout@v2
      with:
        repository: YosysHQ/nextpnr
        ref: master
        path: nextpnr
        submodules: true

    - name: Install nextpnr
      working-directory: nextpnr
      run: |
        cmake -DARCH=ice40 -DCMAKE_INSTALL_PREFIX=/usr/local .
        make
        sudo make install

    - name: Checkout yosys
      uses: actions/checkout@v2
      with:
        repository: YosysHQ/yosys
        ref: master
        path: yosys

    - name: Install yosys
      working-directory: yosys
      run: |
        make
        sudo make install

    - name: Setup Haskell
      uses: haskell/actions/setup@v1
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}

    - name: Install dependencies
      run: |
        cabal update
        cabal build --only-dependencies

    - name: Build
      run: cabal build

    - name: Synthesize
      run: cabal run blinker
